/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef,useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/crown.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    console.log(actions);
    actions.crown.play();
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        name="Cylinder"
        geometry={nodes.Cylinder.geometry}
        material={materials['Material.002']}
        position={[0, -.2, -0.3]}
        
      />
    </group>
  )
}

useGLTF.preload('/crown.glb')
