/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef,useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/didusample.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    console.log(actions);
    actions.sphere.play();
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        name="Sphere"
        geometry={nodes.Sphere.geometry}
        material={materials['Material.001']}
        position={[0, 0, 2]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1, 0.25, 1]}
      />
    </group>
  )
}

useGLTF.preload('/didusample.glb')
